[package]
name = "blockstream_balance_loop"
version = "0.1.0"
edition = "2021"  # Use "2018" if you prefer that edition

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }